import { Calculator, MapPinned, Plus, Route, Truck } from "lucide-react";
import Link from "next/link";
import { redirect } from "next/navigation";
import { createShippingRateAction, toggleShippingRateAction } from "@/app/shipping/actions";
import { AppShell } from "@/components/app-shell";
import { OpsModal } from "@/components/ops-modal";
import { getSession } from "@/lib/session";
import { getShippingPage } from "@/server/operations/shipping";
export default async function ShippingPage({searchParams}:{searchParams:Promise<{zone?:string;weight?:string;create?:string}>}){const session=await getSession();if(!session)redirect('/login');const params=await searchParams;const weight=Math.max(1,Number(params.weight)||1000);const page=await getShippingPage(session.userId,params.zone,weight);return <AppShell active="shipping" businessName={page.businessName}><section className="ops-page"><header className="ops-header"><div><p className="eyebrow">Fulfillment</p><h1>Cek ongkir otomatis</h1><p>Atur zona dan tarif sendiri, lalu hitung ongkir konsisten saat membuat order.</p></div><Link className="primary-button" href="/shipping?create=1"><Plus size={17}/>Tarif baru</Link></header>
<div className="shipping-layout"><section className="ops-card"><div className="ops-card-title"><div className="icon-tile"><Calculator size={20}/></div><div><h2>Kalkulator ongkir</h2><p>Harga dihitung dari tarif dasar + pembulatan kilogram.</p></div></div><form className="quote-form" action="/shipping"><label>Zona tujuan<select name="zone" defaultValue={params.zone??''} required><option value="">Pilih zona</option>{page.zones.map(z=><option key={z} value={z}>{z}</option>)}</select></label><label>Berat (gram)<input name="weight" type="number" min="1" defaultValue={weight}/></label><button className="primary-button">Cek ongkir</button></form><div className="quote-results">{params.zone&&page.quotes.length===0?<p className="muted">Belum ada layanan yang cocok untuk berat ini.</p>:page.quotes.map(q=><div className="quote-card" key={q.id}><Truck size={19}/><div><strong>{q.serviceName}</strong><span>{q.zoneName} · {q.estimatedDays??'Estimasi belum diatur'}</span></div><b>{rupiah(q.price)}</b></div>)}</div></section><section className="ops-card"><div className="ops-card-title"><div className="icon-tile"><Route size={20}/></div><div><h2>Daftar tarif</h2><p>{page.rates.length} layanan tersimpan.</p></div></div><div className="rate-list">{page.rates.map(rate=><div className={rate.isActive?'rate-row':'rate-row disabled'} key={rate.id}><MapPinned size={17}/><div><strong>{rate.zoneName} · {rate.serviceName}</strong><span>{rupiah(rate.basePrice)} + {rupiah(rate.pricePerKg)}/kg</span></div><form action={toggleShippingRateAction}><input type="hidden" name="rateId" value={rate.id}/><button className="table-link-button">{rate.isActive?'Nonaktifkan':'Aktifkan'}</button></form></div>)}</div></section></div>
{params.create?<OpsModal action={createShippingRateAction} closeHref="/shipping" eyebrow="Rate card" id="create-shipping-title" submitLabel="Simpan tarif" title="Tambah tarif"><div className="form-grid"><label>Nama zona<input name="zoneName" required placeholder="Lombok Tengah"/></label><label>Layanan<input name="serviceName" required placeholder="Regular"/></label><label>Berat minimum<input name="minWeightGrams" type="number" min="0" defaultValue="0"/></label><label>Berat maksimum<input name="maxWeightGrams" type="number" min="1" placeholder="Kosong = tanpa batas"/></label><label>Tarif dasar<input name="basePrice" type="number" min="0" required/></label><label>Tambahan per kg<input name="pricePerKg" type="number" min="0" defaultValue="0"/></label><label>Estimasi tiba<input name="estimatedDays" placeholder="1–2 hari"/></label></div><input type="hidden" name="isActive" value="on"/></OpsModal>:null}</section></AppShell>}
function rupiah(value:number){return new Intl.NumberFormat('id-ID',{style:'currency',currency:'IDR',maximumFractionDigits:0}).format(value)}
