import { CheckCircle2, Plus, Tags, UserRoundCheck, Users } from "lucide-react";
import Link from "next/link";
import { redirect } from "next/navigation";
import { createSegmentAction, updateContactAudienceAction } from "@/app/customers/actions";
import { AppShell } from "@/components/app-shell";
import { OpsModal } from "@/components/ops-modal";
import { getSession } from "@/lib/session";
import { getCustomersPage } from "@/server/operations/segments";

export default async function CustomersPage({searchParams}:{searchParams:Promise<{segment?:string;create?:string}>}){const session=await getSession();if(!session)redirect('/login');const params=await searchParams;const page=await getCustomersPage(session.userId,params.segment);const optedIn=page.contacts.filter(c=>c.marketingOptInAt&&!c.marketingOptOutAt).length;const readOnly=session.role==='VIEWER';const canManageSegments=session.role==='OWNER'||session.role==='ADMIN';return <AppShell active="customers" businessName={page.businessName} workspaceRole={session.role??'VIEWER'}><section className="ops-page">
<header className="ops-header"><div><p className="eyebrow">Customer data</p><h1>Pelanggan & segmentasi</h1><p>Kelompokkan customer, kelola consent, dan siapkan audience yang relevan.</p></div>{canManageSegments?<Link className="primary-button" href="/customers?create=1"><Plus size={17}/>Segmen baru</Link>:null}</header>
<div className="ops-metrics"><Metric icon={Users} label="Kontak terlihat" value={page.contacts.length}/><Metric icon={Tags} label="Segmen" value={page.segments.length}/><Metric icon={UserRoundCheck} label="Opt-in marketing" value={optedIn}/></div>
<div className="segment-strip"><Link className={!params.segment?'active':''} href="/customers">Semua pelanggan</Link>{page.segments.map(s=><Link className={params.segment===s.id?'active':''} href={`/customers?segment=${s.id}`} key={s.id}><span style={{background:s.color}}/>{s.name}<small>{s._count.memberships}</small></Link>)}</div>
<div className="data-table-card"><div className="data-table customer-table"><div className="data-table-head"><span>Pelanggan</span><span>Segmen</span><span>Consent WhatsApp</span><span>Aksi</span></div>{page.contacts.length===0?<div className="ops-empty"><Users size={28}/><h2>Belum ada customer</h2><p>Kontak otomatis dibuat dari chat masuk.</p></div>:page.contacts.map(contact=><div className="data-table-row" key={contact.id}><span><strong>{contact.displayName??'Tanpa nama'}</strong><small>{contact.phoneNumber}</small></span><span className="inline-tags">{contact.segmentMemberships.length?contact.segmentMemberships.map(m=><em style={{borderColor:m.segment.color}} key={m.segmentId}>{m.segment.name}</em>):<small>Belum dikelompokkan</small>}</span><span>{contact.marketingOptInAt&&!contact.marketingOptOutAt?<span className="consent-badge"><CheckCircle2 size={14}/>Opt-in</span>:<span className="status status-warning">Belum opt-in</span>}</span><span>{readOnly?<small className="muted">Hanya lihat</small>:<form className="inline-action-form" action={updateContactAudienceAction}><input type="hidden" name="contactId" value={contact.id}/><select name="segmentId"><option value="">Pilih segmen</option>{page.segments.map(s=><option value={s.id} key={s.id}>{s.name}</option>)}</select><button className="small-outline-button" name="audienceAction" value="ADD_SEGMENT">Tambah</button><button className="table-link-button" name="audienceAction" value={contact.marketingOptInAt&&!contact.marketingOptOutAt?'OPT_OUT':'OPT_IN'}>{contact.marketingOptInAt&&!contact.marketingOptOutAt?'Cabut consent':'Catat opt-in'}</button></form>}</span></div>)}</div></div>
{canManageSegments&&params.create?<OpsModal action={createSegmentAction} closeHref="/customers" eyebrow="Audience" id="create-segment-title" size="compact" submitLabel="Simpan segmen" title="Buat segmen"><label>Nama segmen<input name="name" maxLength={80} required placeholder="Contoh: Pelanggan villa"/></label><label>Deskripsi<textarea name="description" rows={3}/></label><label>Warna<input name="color" type="color" defaultValue="#2563eb"/></label></OpsModal>:null}
</section></AppShell>}
function Metric({icon:Icon,label,value}:{icon:typeof Users;label:string;value:number}){return <div className="ops-metric"><Icon size={19}/><span>{label}</span><strong>{value}</strong></div>}
