import { BellRing, Bot, GitBranch, Play, Plus, Tag, UserRoundCheck, Workflow } from "lucide-react";
import Link from "next/link";
import { redirect } from "next/navigation";
import { createWorkflowAction, toggleWorkflowAction } from "@/app/workflows/actions";
import { AppShell } from "@/components/app-shell";
import { OpsModal } from "@/components/ops-modal";
import { WorkflowStatus } from "@/generated/prisma-beta/client";
import { getSession } from "@/lib/session";
import { getWorkflowsPage, normalizeWorkflowSteps } from "@/server/operations/workflows";

const triggerLabels:Record<string,string>={CUSTOMER_MESSAGE:'Pesan customer masuk',COMPLAINT_CREATED:'Komplain dibuat',ORDER_CREATED:'Order baru dibuat'};
const actionLabels:Record<string,string>={ADD_CONTACT_TAG:'Tambah tag pelanggan',CREATE_COMPLAINT:'Buat ticket komplain',REQUEST_HUMAN:'Alihkan ke tim',NOTIFY_TEAM:'Kirim notifikasi internal'};
export default async function WorkflowsPage({searchParams}:{searchParams:Promise<{create?:string}>}){const session=await getSession();if(!session)redirect('/login');const params=await searchParams;const page=await getWorkflowsPage(session.userId);return <AppShell active="workflows" businessName={page.businessName}><section className="ops-page"><header className="ops-header"><div><p className="eyebrow">No-code automation</p><h1>Workflow builder</h1><p>Susun trigger dan aksi operasional tanpa mengubah kode.</p></div><Link className="primary-button" href="/workflows?create=1"><Plus size={17}/>Workflow baru</Link></header>
<div className="workflow-list">{page.workflows.length===0?<div className="ops-empty"><Workflow size={30}/><h2>Belum ada workflow</h2><p>Mulai dari alur sederhana: pesan masuk → beri tag → beri tahu tim.</p></div>:page.workflows.map(flow=>{const steps=normalizeWorkflowSteps(flow.steps);return <article className="workflow-card" key={flow.id}><div className="workflow-card-head"><div><span className={`campaign-status ${flow.status.toLowerCase()}`}>{label(flow.status)}</span><h2>{flow.name}</h2><p>{flow.description??'Workflow operasional Aijou'}</p></div><form action={toggleWorkflowAction}><input type="hidden" name="workflowId" value={flow.id}/><button className={flow.status===WorkflowStatus.ACTIVE?'ghost-button':'primary-button'}>{flow.status===WorkflowStatus.ACTIVE?'Jeda':'Aktifkan'}</button></form></div><div className="workflow-canvas"><Node icon={Play} eyebrow="Trigger" label={triggerLabels[flow.triggerType]??flow.triggerType}/>{steps.map((step,index)=><div className="workflow-node-wrap" key={`${step.type}-${index}`}><span className="workflow-connector"/><Node icon={actionIcon(step.type)} eyebrow={`Aksi ${index+1}`} label={actionLabels[step.type]??step.type} detail={step.value}/></div>)}</div><footer><span>{flow.runCount} kali berjalan</span><span>{flow.lastRunAt?`Terakhir ${formatDate(flow.lastRunAt)}`:'Belum pernah berjalan'}</span>{flow.lastError?<span className="danger-text">{flow.lastError}</span>:null}</footer></article>})}</div>
{params.create?<OpsModal action={createWorkflowAction} closeHref="/workflows" eyebrow="Builder" id="create-workflow-title" size="wide" submitLabel="Simpan workflow" title="Workflow baru"><div className="form-grid"><label>Nama workflow<input name="name" required maxLength={120} placeholder="Tandai lead prioritas"/></label><label>Trigger<select name="triggerType" defaultValue="CUSTOMER_MESSAGE">{Object.entries(triggerLabels).map(([value,text])=><option value={value} key={value}>{text}</option>)}</select></label><label className="span-2">Deskripsi<input name="description" maxLength={500}/></label></div><div className="builder-stack"><div className="builder-node trigger"><Play size={18}/><span><small>Ketika</small>Trigger di atas terjadi</span></div>{[1,2,3].map((index)=><div className="builder-node" key={index}><span className="builder-index">{index}</span><label>Aksi<select name={`step_${index}_type`} defaultValue={index===1?'NOTIFY_TEAM':''}><option value="">Tidak digunakan</option>{Object.entries(actionLabels).map(([v,t])=><option value={v} key={v}>{t}</option>)}</select></label><label>Nilai / pesan<input name={`step_${index}_value`} placeholder="Tag atau isi notifikasi"/></label></div>)}</div><label className="toggle-row"><input type="checkbox" name="activateNow"/><span><strong>Aktifkan setelah disimpan</strong><small>Workflow langsung merespons event baru.</small></span></label></OpsModal>:null}</section></AppShell>}
function Node({icon:Icon,eyebrow,label:nodeLabel,detail}:{icon:typeof Play;eyebrow:string;label:string;detail?:string}){return <div className="workflow-node"><span><Icon size={18}/></span><div><small>{eyebrow}</small><strong>{nodeLabel}</strong>{detail?<em>{detail}</em>:null}</div></div>}
function actionIcon(type:string){if(type==='ADD_CONTACT_TAG')return Tag;if(type==='REQUEST_HUMAN')return UserRoundCheck;if(type==='NOTIFY_TEAM')return BellRing;if(type==='CREATE_COMPLAINT')return Bot;return GitBranch}
function label(value:string){return value.toLowerCase().split('_').map(p=>p[0].toUpperCase()+p.slice(1)).join(' ')}
function formatDate(value:Date){return new Intl.DateTimeFormat('id-ID',{dateStyle:'medium',timeStyle:'short',timeZone:'Asia/Makassar'}).format(value)}
