import { CircleDollarSign, PackageCheck, Plus, ShoppingBag, Truck } from "lucide-react";
import Link from "next/link";
import { redirect } from "next/navigation";
import { createOrderAction, updateOrderStatusAction } from "@/app/orders/actions";
import { AppShell } from "@/components/app-shell";
import { OpsModal } from "@/components/ops-modal";
import { OrderStatus, ShipmentStatus } from "@/generated/prisma-beta/client";
import { getSession } from "@/lib/session";
import { getOrdersPage } from "@/server/operations/orders";

export default async function OrdersPage({searchParams}:{searchParams:Promise<{create?:string}>}){const session=await getSession();if(!session)redirect('/login');const params=await searchParams;const page=await getOrdersPage(session.userId);const revenue=page.orders.filter(o=>o.status!==OrderStatus.CANCELLED).reduce((n,o)=>n+Number(o.totalAmount),0);const readOnly=session.role==='VIEWER';return <AppShell active="orders" businessName={page.businessName} workspaceRole={session.role??'VIEWER'}><section className="ops-page">
<header className="ops-header"><div><p className="eyebrow">Order operations</p><h1>Pesanan & fulfillment</h1><p>Kelola item, ongkir, pembayaran manual, dan progres pengiriman tanpa Xendit.</p></div>{!readOnly?<Link className="primary-button" href="/orders?create=1"><Plus size={17}/>Buat order</Link>:null}</header>
{/* @ts-expect-error Prisma enum is intentionally narrowed to active fulfillment states. */}
<div className="ops-metrics"><Metric icon={ShoppingBag} label="Total order" value={page.orders.length}/><Metric icon={PackageCheck} label="Diproses" value={page.orders.filter(o=>[OrderStatus.CONFIRMED,OrderStatus.PROCESSING,OrderStatus.READY].includes(o.status)).length}/><Metric icon={Truck} label="Dikirim" value={page.orders.filter(o=>o.shipmentStatus===ShipmentStatus.SHIPPED).length}/><Metric icon={CircleDollarSign} label="Nilai order" value={rupiah(revenue)}/></div>
<div className="order-board">{page.orders.length===0?<div className="ops-empty"><ShoppingBag size={30}/><h2>Belum ada order</h2><p>Buat order manual atau biarkan workflow membuat tindak lanjut dari chat.</p></div>:page.orders.map(order=><article className="order-card" key={order.id}><div className="order-card-head"><div><span className="ticket-number">{order.orderNumber}</span><h2>{order.customerName}</h2><p>{order.customerPhone??order.customerEmail??'Tanpa kontak'}</p></div><strong>{rupiah(Number(order.totalAmount))}</strong></div><div className="order-items">{order.items.map(item=><span key={item.id}>{item.quantity}× {item.name}</span>)}</div><div className="order-status-line"><span className="campaign-status">{label(order.status)}</span><span>{order.shippingService?`${order.shippingService} · ${label(order.shipmentStatus)}`:'Tanpa pengiriman'}</span><span>{order.paymentStatus}</span></div>{!readOnly?<form className="order-update-form" action={updateOrderStatusAction}><input type="hidden" name="orderId" value={order.id}/><select name="status" defaultValue={order.status}>{Object.values(OrderStatus).map(v=><option value={v} key={v}>{label(v)}</option>)}</select><select name="shipmentStatus" defaultValue={order.shipmentStatus}>{Object.values(ShipmentStatus).map(v=><option value={v} key={v}>{label(v)}</option>)}</select><select name="paymentStatus" defaultValue={order.paymentStatus}><option value="UNPAID">Belum dibayar</option><option value="PARTIAL">Sebagian</option><option value="PAID">Lunas</option><option value="REFUNDED">Refund</option></select><input name="trackingNumber" defaultValue={order.trackingNumber??''} placeholder="Nomor resi"/><button className="small-outline-button">Simpan</button></form>:<small className="muted">Mode hanya lihat</small>}</article>)}</div>
{!readOnly&&params.create?<OpsModal action={createOrderAction} closeHref="/orders" eyebrow="Order baru" id="create-order-title" size="wide" submitLabel="Buat order" title="Detail pesanan"><div className="form-grid"><label>Nama customer<input name="customerName" required maxLength={160}/></label><label>Nomor WhatsApp<input name="customerPhone" placeholder="62812…"/></label><label>Email<input name="customerEmail" type="email"/></label><label>Produk<select name="productId"><option value="">Item custom</option>{page.products.map(p=><option value={p.id} key={p.id}>{p.name} · {rupiah(Number(p.price))}</option>)}</select></label><label>Nama item custom<input name="itemName" placeholder="Isi jika tanpa produk"/></label><label>Harga satuan<input name="unitPrice" type="number" min="0" defaultValue="0"/></label><label>Jumlah<input name="quantity" type="number" min="1" max="999" defaultValue="1"/></label><label>Diskon<input name="discountAmount" type="number" min="0" defaultValue="0"/></label><label>Berat total (gram)<input name="weightGrams" type="number" min="0" defaultValue="1000"/></label><label>Layanan ongkir<select name="shippingRateId"><option value="">Tanpa ongkir</option>{page.rates.map(r=><option value={r.id} key={r.id}>{r.zoneName} · {r.serviceName} · mulai {rupiah(Number(r.basePrice))}</option>)}</select></label><label className="span-2">Alamat pengiriman<textarea name="shippingAddress" rows={3}/></label><label className="span-2">Catatan<textarea name="notes" rows={2}/></label></div><label className="toggle-row"><input type="checkbox" name="confirmNow"/><span><strong>Konfirmasi order sekarang</strong><small>Jika tidak, order disimpan sebagai draft.</small></span></label></OpsModal>:null}
</section></AppShell>}
function Metric({icon:Icon,label:labelText,value}:{icon:typeof ShoppingBag;label:string;value:number|string}){return <div className="ops-metric"><Icon size={19}/><span>{labelText}</span><strong>{value}</strong></div>}
function rupiah(value:number){return new Intl.NumberFormat('id-ID',{style:'currency',currency:'IDR',maximumFractionDigits:0}).format(value)}
function label(value:string){return value.toLowerCase().split('_').map(p=>p[0].toUpperCase()+p.slice(1)).join(' ')}
