import { Megaphone, MessageSquareLock, Plus, Send, ShieldCheck, Users } from "lucide-react";
import Link from "next/link";
import { redirect } from "next/navigation";
import { createBroadcastAction, pauseBroadcastAction, startBroadcastAction } from "@/app/broadcasts/actions";
import { AppShell } from "@/components/app-shell";
import { OpsModal } from "@/components/ops-modal";
import { BroadcastStatus } from "@/generated/prisma-beta/client";
import { getSession } from "@/lib/session";
import { getBroadcastsPage } from "@/server/operations/broadcasts";

export default async function BroadcastsPage({searchParams}:{searchParams:Promise<{create?:string}>}){const session=await getSession();if(!session)redirect('/login');const params=await searchParams;const page=await getBroadcastsPage(session.userId);return <AppShell active="broadcasts" businessName={page.businessName}><section className="ops-page">
<header className="ops-header"><div><p className="eyebrow">WhatsApp marketing</p><h1>Broadcast yang aman</h1><p>Kirim approved template hanya ke pelanggan yang tercatat memberikan opt-in.</p></div><Link className="primary-button" href="/broadcasts?create=1"><Plus size={17}/>Campaign baru</Link></header>
<div className="compliance-banner"><ShieldCheck size={22}/><div><strong>Guardrail Meta aktif</strong><p>Nomor tanpa opt-in otomatis dilewati. Campaign selalu memakai template WhatsApp yang sudah disetujui dan dikirim bertahap melalui antrean.</p></div></div>
<div className="ops-metrics"><Metric icon={Users} label="Audience opt-in" value={page.optedInCount}/><Metric icon={Megaphone} label="Campaign" value={page.campaigns.length}/><Metric icon={Send} label="Pesan terkirim" value={page.campaigns.reduce((n,c)=>n+c.sentCount,0)}/><Metric icon={MessageSquareLock} label="WhatsApp" value={page.whatsAppReady?'Siap':'Belum siap'}/></div>
{/* @ts-expect-error Prisma enum is intentionally narrowed to restartable campaign states. */}
<div className="campaign-list">{page.campaigns.length===0?<div className="ops-empty"><Megaphone size={30}/><h2>Belum ada campaign</h2><p>Buat draft pertama. Tidak ada pesan yang terkirim sebelum lu menekan mulai.</p></div>:page.campaigns.map(c=><article className="campaign-card" key={c.id}><div className="campaign-main"><span className={`campaign-status ${c.status.toLowerCase()}`}>{label(c.status)}</span><h2>{c.name}</h2><p>Template <code>{c.templateName}</code> · {c.segment?.name??'Semua kontak opt-in'}</p></div><div className="campaign-progress"><div><span>Terkirim</span><strong>{c.sentCount}/{c.totalRecipients}</strong></div><progress max={Math.max(1,c.totalRecipients)} value={c.sentCount}/><small>{c.failedCount} gagal</small></div><div className="campaign-actions">{[BroadcastStatus.DRAFT,BroadcastStatus.PAUSED,BroadcastStatus.FAILED].includes(c.status)?<form action={startBroadcastAction}><input type="hidden" name="campaignId" value={c.id}/><button className="primary-button" disabled={!page.whatsAppReady||page.optedInCount===0}>Mulai aman</button></form>:null}{c.status===BroadcastStatus.RUNNING?<form action={pauseBroadcastAction}><input type="hidden" name="campaignId" value={c.id}/><button className="ghost-button">Jeda</button></form>:null}</div></article>)}</div>
{params.create?<OpsModal action={createBroadcastAction} closeHref="/broadcasts" eyebrow="Draft campaign" id="create-broadcast-title" submitLabel="Simpan draft" title="Broadcast WhatsApp"><label>Nama campaign<input name="name" required maxLength={120} placeholder="Promo Agustus"/></label><div className="form-grid"><label>Audience<select name="segmentId"><option value="">Semua kontak opt-in</option>{page.segments.map(s=><option value={s.id} key={s.id}>{s.name} ({s._count.memberships})</option>)}</select></label><label>Kode bahasa<input name="languageCode" defaultValue="id" required/></label></div><label>Nama approved template Meta<input name="templateName" pattern="[a-z0-9_]{1,512}" required placeholder="promo_agustus"/><small>Harus sama persis dengan template berstatus Approved di WhatsApp Manager.</small></label><label>Parameter body <small>satu nilai per baris, maksimal 10</small><textarea name="bodyParameters" rows={5} placeholder={'Nama pelanggan\nKode promo'}/></label><div className="compliance-check"><ShieldCheck size={18}/><span>Campaign dibuat sebagai draft. Pengiriman hanya dimulai lewat tombol “Mulai aman”.</span></div></OpsModal>:null}
</section></AppShell>}
function Metric({icon:Icon,label:labelText,value}:{icon:typeof Users;label:string;value:number|string}){return <div className="ops-metric"><Icon size={19}/><span>{labelText}</span><strong>{value}</strong></div>}
function label(value:string){return value.toLowerCase().split('_').map(p=>p[0].toUpperCase()+p.slice(1)).join(' ')}
