import { CheckCircle2, Megaphone, MessageSquareLock, Plus, Send, ShieldCheck, TriangleAlert, Users } from "lucide-react";
import Link from "next/link";
import { redirect } from "next/navigation";
import { createBroadcastAction, pauseBroadcastAction, startBroadcastAction } from "@/app/broadcasts/actions";
import { AppShell } from "@/components/app-shell";
import { BroadcastComposerFields } from "@/components/broadcast-composer-fields";
import { FormSubmitButton } from "@/components/form-submit-button";
import { OpsModal } from "@/components/ops-modal";
import { BroadcastKind, BroadcastStatus } from "@/generated/prisma-beta/client";
import { getSession } from "@/lib/session";
import { getBroadcastsPage } from "@/server/operations/broadcasts";

export default async function BroadcastsPage({searchParams}:{searchParams:Promise<{create?:string;created?:string;error?:string;started?:string;updated?:string}>}){const session=await getSession();if(!session)redirect('/login');const params=await searchParams;const page=await getBroadcastsPage(session.userId);return <AppShell active="broadcasts" businessName={page.businessName}><section className="ops-page">
<header className="ops-header"><div><p className="eyebrow">WhatsApp marketing</p><h1>Broadcast yang aman</h1><p>Kirim approved template hanya ke pelanggan yang tercatat memberikan opt-in.</p></div><Link className="primary-button" href="/broadcasts?create=1"><Plus size={17}/>Campaign baru</Link></header>
<div className="compliance-banner"><ShieldCheck size={22}/><div><strong>Guardrail Meta aktif</strong><p>Nomor tanpa consent atau yang baru menerima promosi otomatis dilewati. Campaign memakai template approved Meta, dikirim bertahap, dan berhenti otomatis bila Meta mengembalikan error pembatasan.</p></div></div>
{params.started?<div className="broadcast-feedback is-success" role="status"><CheckCircle2 size={18}/><span>Broadcast dimulai. Pesan sedang dikirim bertahap oleh sistem.</span></div>:null}{params.created?<div className="broadcast-feedback is-success" role="status"><CheckCircle2 size={18}/><span>Draft broadcast berhasil disimpan.</span></div>:null}{params.updated?<div className="broadcast-feedback is-success" role="status"><CheckCircle2 size={18}/><span>Campaign berhasil diperbarui.</span></div>:null}{params.error?<div className="broadcast-feedback is-error" role="alert"><TriangleAlert size={18}/><span>{params.error}</span></div>:null}
<div className="ops-metrics"><Metric icon={Users} label="Audience opt-in" value={page.optedInCount}/><Metric icon={Megaphone} label="Campaign" value={page.campaigns.length}/><Metric icon={Send} label="Pesan terkirim" value={page.campaigns.reduce((n,c)=>n+c.sentCount,0)}/><Metric icon={MessageSquareLock} label="WhatsApp" value={page.whatsAppReady?'Siap':'Belum siap'}/></div>
{/* @ts-expect-error Prisma enum is intentionally narrowed to restartable campaign states. */}
<div className="campaign-list">{page.campaigns.length===0?<div className="ops-empty"><Megaphone size={30}/><h2>Belum ada campaign</h2><p>Buat draft pertama. Tidak ada pesan yang terkirim sebelum lu menekan mulai.</p></div>:page.campaigns.map(c=><article className="campaign-card" key={c.id}><div className="campaign-main"><span className={`campaign-status ${c.status.toLowerCase()}`}>{label(c.status)}</span><h2>{c.name}</h2><p>{c.kind===BroadcastKind.CONSENT_REQUEST?"Permintaan izin promo · hanya customer yang chat dalam 24 jam":<>Template <code>{c.templateName}</code> · {c.segment?.name??(c._count.recipients?'Nomor manual':'Semua kontak opt-in')}</>}</p></div><div className="campaign-progress"><div><span>Terkirim</span><strong>{c.sentCount}/{c.totalRecipients}</strong></div><progress max={Math.max(1,c.totalRecipients)} value={c.sentCount}/><small>{c.failedCount} gagal</small></div><div className="campaign-actions">{[BroadcastStatus.DRAFT,BroadcastStatus.PAUSED,BroadcastStatus.FAILED].includes(c.status)?<><form action={startBroadcastAction}><input type="hidden" name="campaignId" value={c.id}/><FormSubmitButton className="primary-button" label="Mulai aman" pendingLabel="Menyiapkan…" disabled={!page.whatsAppReady||(c.kind===BroadcastKind.CONSENT_REQUEST?page.recentChatCount===0:page.optedInCount===0)}/></form>{!page.whatsAppReady?<small className="campaign-action-hint">Hubungkan WhatsApp dulu.</small>:c.kind===BroadcastKind.CONSENT_REQUEST&&page.recentChatCount===0?<small className="campaign-action-hint">Belum ada customer yang chat dalam 24 jam.</small>:c.kind!==BroadcastKind.CONSENT_REQUEST&&page.optedInCount===0?<small className="campaign-action-hint">Belum ada kontak opt-in.</small>:null}</>:null}{c.status===BroadcastStatus.RUNNING?<form action={pauseBroadcastAction}><input type="hidden" name="campaignId" value={c.id}/><FormSubmitButton className="ghost-button" label="Jeda" pendingLabel="Menjeda…"/></form>:null}</div></article>)}</div>
{params.create?<OpsModal action={createBroadcastAction} closeHref="/broadcasts" eyebrow="Draft campaign" id="create-broadcast-title" submitLabel="Simpan draft" title="Broadcast WhatsApp"><label>Nama campaign<input name="name" required maxLength={120} placeholder="Promo Agustus"/></label><BroadcastComposerFields optedInCount={page.optedInCount} recentChatCount={page.recentChatCount} templates={page.templates} templateError={page.templateError}/><div className="compliance-check"><ShieldCheck size={18}/><span>Campaign promo hanya memakai template approved Meta dan kontak opt-in. Mode minta izin tidak mengirim promo sebelum customer menyetujui.</span></div></OpsModal>:null}
</section></AppShell>}
function Metric({icon:Icon,label:labelText,value}:{icon:typeof Users;label:string;value:number|string}){return <div className="ops-metric"><Icon size={19}/><span>{labelText}</span><strong>{value}</strong></div>}
function label(value:string){return value.toLowerCase().split('_').map(p=>p[0].toUpperCase()+p.slice(1)).join(' ')}
