ALTER TYPE "AuthTokenPurpose" ADD VALUE IF NOT EXISTS 'PHONE_VERIFICATION';
ALTER TYPE "AuthTokenPurpose" ADD VALUE IF NOT EXISTS 'WHATSAPP_PASSWORD_RESET';

ALTER TABLE "users" ADD COLUMN "recoveryPhoneVerifiedAt" TIMESTAMP(3);
ALTER TABLE "auth_tokens" ADD COLUMN "phoneNumber" TEXT;
